In [10]:
# Importa a biblioteca específica do Colab para acessar o Google Drive
import pandas as pd
import numpy as np
import time

import jinja2

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
# Definindo os caminho da nova pasta no PC pessoal
caminho_pasta_tratado = '../../dataset tratado/cicids2017/Sem Redução de Dimensionalidade'

nome_dados_treinamento = 'cicids2017_treinamento.csv'
nome_dados_teste = 'cicids2017_teste.csv'

In [12]:
# 1. Carregando o input a partir dos CSVs de dados JÁ TRATADOS
print("Carregando os datasets tratados em CSV...")
df_treino = pd.read_csv(caminho_pasta_tratado + "/" + nome_dados_treinamento)
df_teste = pd.read_csv(caminho_pasta_tratado + "/" + nome_dados_teste)

print(f"Dados carregados! Treino: {df_treino.shape} | Teste: {df_teste.shape}")

display(df_treino.head())
display(df_teste.head())

Carregando os datasets tratados em CSV...
Dados carregados! Treino: (1979513, 81) | Teste: (848363, 81)

,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0.006760,0.855604,0.352941,3.229166e-05,0.000009,0.000003,2.945736e-06,9.153974e-09,0.001531,0.000000,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
1,0.625956,0.006760,0.352941,2.272266e-03,0.000009,0.000017,0.000000e+00,4.576987e-09,0.000000,0.000000,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2,0.006760,0.848402,0.352941,1.333333e-07,0.000005,0.000000,9.302326e-07,0.000000e+00,0.000242,0.002581,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3,0.801816,0.000809,1.000000,1.233333e-06,0.000005,0.000007,6.821705e-06,1.830795e-07,0.001773,0.018925,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
4,0.583032,0.000809,1.000000,1.449567e-03,0.000005,0.000007,4.496124e-06,3.509023e-07,0.001168,0.012473,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0.001221,0.585107,0.352941,9.205005e-02,0.000000,0.000017,4.651163e-07,4.576987e-08,0.000242,0.002581,...,1.0,0.000342,0.000000,0.000342,0.000342,0.091667,0.000000,0.091667,0.091667,BENIGN
1,0.909133,0.001221,0.352941,1.276342e-03,0.000009,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,...,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,BENIGN
2,0.862333,0.006760,0.352941,5.102475e-01,0.000086,0.000062,1.924031e-04,1.157062e-05,0.024013,0.000000,...,1.0,0.001497,0.003769,0.006687,0.000459,0.083290,0.000132,0.083333,0.083136,BENIGN
3,0.868467,0.000809,1.000000,9.841666e-06,0.000005,0.000007,7.286822e-06,3.356457e-07,0.001894,0.020215,...,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,BENIGN
4,0.006760,0.650904,0.352941,4.666666e-07,0.000000,0.000003,0.000000e+00,0.000000e+00,0.000000,0.000000,...,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,BENIGN

In [13]:
# 2. Separando as Features (variáveis numéricas já normalizadas) da Label (gabarito)
X_treino = df_treino.drop('Label', axis=1)
y_treino = df_treino['Label']

X_teste = df_teste.drop('Label', axis=1)
y_teste = df_teste['Label']

print(f"Dados prontos! Treino: {X_treino.shape} | Teste: {X_teste.shape}")

Dados prontos! Treino: (1979513, 80) | Teste: (848363, 80)

In [14]:
# 3. Instanciando o modelo Random Forest (conforme metodologia do TCC)
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)

# 4. Treinamento medindo o custo computacional
print("\nIniciando o treinamento do Random Forest...")
inicio_treino = time.time()

rf_model.fit(X_treino, y_treino)

fim_treino = time.time()
tempo_treinamento = fim_treino - inicio_treino
print(f"Treinamento concluído! Tempo total: {tempo_treinamento:.4f} segundos.")

Iniciando o treinamento do Random Forest...
Treinamento concluído! Tempo total: 125.9007 segundos.

In [15]:

# 5. Classificação (Teste) medindo o tempo de previsão
print("\nIniciando a classificação dos dados de teste...")
inicio_teste = time.time()

previsoes = rf_model.predict(X_teste)

fim_teste = time.time()
tempo_teste = fim_teste - inicio_teste
print(f"Classificação concluída! Tempo de previsão: {tempo_teste:.4f} segundos.")

# 6. Avaliação dos Resultados
print("\n=== MATRIZ DE CONFUSÃO ===")

labels = sorted(np.unique(np.concatenate([y_teste.values, previsoes])))
cm = confusion_matrix(y_teste, previsoes, labels=labels)

cm_df = pd.DataFrame(
    cm,
    index=[f"Real_{lbl}" for lbl in labels],
    columns=[f"Pred_{lbl}" for lbl in labels]
)

def color_confusion_matrix(data):
    styles = pd.DataFrame("", index=data.index, columns=data.columns)

    # Green diagonal (correct predictions)
    for i in range(min(data.shape[0], data.shape[1])):
        styles.iat[i, i] = "background-color: #c6efce; color: #006100; font-weight: bold;"

    # Red off-diagonal only when value != 0 (errors)
    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            if i != j and data.iat[i, j] != 0:
                styles.iat[i, j] = "background-color: #ffc7ce; color: #9c0006; font-weight: bold;"

    return styles

display(
    cm_df.style
        .apply(color_confusion_matrix, axis=None)
        .format("{:.0f}")
)

print("\n=== RELATÓRIO DE MÉTRICAS (Precisão, Recall, F1-Score) ===")
print(classification_report(y_teste, previsoes))

Iniciando a classificação dos dados de teste...
Classificação concluída! Tempo de previsão: 3.5401 segundos.

=== MATRIZ DE CONFUSÃO ===

=== RELATÓRIO DE MÉTRICAS (Precisão, Recall, F1-Score) ===
                            precision    recall  f1-score   support

                    BENIGN       1.00      1.00      1.00    681014
                       Bot       0.99      0.94      0.96       564
                      DDoS       1.00      1.00      1.00     38307
             DoS GoldenEye       1.00      1.00      1.00      3163
                  DoS Hulk       1.00      1.00      1.00     69267
          DoS Slowhttptest       0.99      0.99      0.99      1658
             DoS slowloris       1.00      1.00      1.00      1757
               FTP-Patator       1.00      1.00      1.00      2326
                Heartbleed       1.00      0.67      0.80         6
              Infiltration       1.00      0.90      0.95        10
                  PortScan       0.99      1.00      1.00     47836
               SSH-Patator       1.00      1.00      1.00      1821
  Web Attack – Brute Force       0.87      0.90      0.88       435
Web Attack – Sql Injection       1.00      0.17      0.29         6
          Web Attack – XSS       0.76      0.64      0.69       193

                  accuracy                           1.00    848363
                 macro avg       0.97      0.88      0.90    848363
              weighted avg       1.00      1.00      1.00    848363

In [16]:
# 7. Exportacao das tabelas em formato LaTeX
from IPython.display import Markdown, display

CLASS_ALIASES_LATEX = {'BENIGN': 'BENIGN', 'Bot': 'Bot', 'DDoS': 'DDoS', 'DoS GoldenEye': 'DoS GE', 'DoS Hulk': 'Hulk', 'DoS Slowhttptest': 'Slowhttp', 'DoS slowloris': 'Slowloris', 'FTP-Patator': 'FTP', 'Heartbleed': 'Heart', 'Infiltration': 'Infil', 'PortScan': 'PortScan', 'SSH-Patator': 'SSH', 'Web Attack - Brute Force': 'Brute', 'Web Attack - Sql Injection': 'SQL', 'Web Attack - XSS': 'XSS', 'Desconhecido': 'Desconh'}


def escape_latex(value):
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in str(value))


def latex_class_name(label, short=False):
    if short:
        return escape_latex(CLASS_ALIASES_LATEX.get(label, label))
    return escape_latex(label)


def format_confusion_value(value, is_diagonal):
    value = int(value)
    if is_diagonal:
        return rf"\ok{{{value}}}"
    if value != 0:
        return rf"\err{{{value}}}"
    return "0"


def make_latex_confusion_matrix(cm_values, class_labels, caption, table_label):
    headers = [latex_class_name(label, short=True) for label in class_labels]
    rows = []
    for i, real_label in enumerate(class_labels):
        row_values = [format_confusion_value(cm_values[i][j], i == j) for j in range(len(class_labels))]
        rows.append((rf"Real\_{latex_class_name(real_label, short=True)}", row_values))

    first_col_width = max([0] + [len(row_name) for row_name, _ in rows])
    col_widths = [max(len(headers[i]), *(len(values[i]) for _, values in rows)) for i in range(len(headers))]

    def format_row(first_cell, values):
        first = first_cell.ljust(first_col_width)
        rest = " & ".join(str(value).ljust(col_widths[i]) for i, value in enumerate(values))
        return f"            {first} & {rest} \\\\"

    lines = [
        r"\begin{table}[H]",
        r"    \centering",
        r"    \scriptsize",
        r"    \resizebox{\linewidth}{!}{",
        rf"        \begin{{tabular}}{{l|{'r' * len(class_labels)}}}",
        r"            \hline",
        format_row("", headers),
        r"            \hline",
    ]
    lines.extend(format_row(row_name, row_values) for row_name, row_values in rows)
    lines.extend([
        r"            \hline",
        r"        \end{tabular}",
        r"    }",
        rf"    \caption{{{escape_latex(caption)}}}",
        rf"    \label{{{table_label}}}",
        r"\end{table}",
    ])
    return "\n".join(lines)


def format_metric(value):
    return "-" if value is None else f"{value:.2f}"


def make_latex_metrics_report(y_true_values, y_pred_values, class_labels, caption, table_label):
    report = classification_report(
        y_true_values,
        y_pred_values,
        labels=class_labels,
        output_dict=True,
        zero_division=0,
    )
    total_support = int(sum(report[label]["support"] for label in class_labels))
    rows = []
    for label in class_labels:
        metrics = report[label]
        rows.append([
            latex_class_name(label),
            format_metric(metrics["precision"]),
            format_metric(metrics["recall"]),
            format_metric(metrics["f1-score"]),
            str(int(metrics["support"])),
        ])

    rows.extend([
        [r"\textbf{Acur?cia}", "-", format_metric(report["accuracy"]), "-", str(total_support)],
        [r"\textbf{M?dia Macro}", format_metric(report["macro avg"]["precision"]), format_metric(report["macro avg"]["recall"]), format_metric(report["macro avg"]["f1-score"]), str(total_support)],
        [r"\textbf{M?dia Ponderada}", format_metric(report["weighted avg"]["precision"]), format_metric(report["weighted avg"]["recall"]), format_metric(report["weighted avg"]["f1-score"]), str(total_support)],
    ])

    headers = ["Classe", "Precis?o", "Revoca??o", "F1-score", "Suporte"]
    col_widths = [max(len(str(row[i])) for row in [headers] + rows) for i in range(len(headers))]

    def format_row(values):
        return "        " + " & ".join(str(value).ljust(col_widths[i]) for i, value in enumerate(values)) + r" \\"

    lines = [
        r"\begin{table}[H]",
        r"    \centering",
        r"    \small",
        r"    \begin{tabular}{lrrrr}",
        r"        \hline",
        format_row(headers),
        r"        \hline",
    ]
    lines.extend(format_row(row) for row in rows[:len(class_labels)])
    lines.extend([
        r"        \hline",
        format_row(rows[-3]),
        format_row(rows[-2]),
        format_row(rows[-1]),
        r"        \hline",
        r"    \end{tabular}",
        rf"    \caption{{{escape_latex(caption)}}}",
        rf"    \label{{{table_label}}}",
        r"\end{table}",
    ])
    return "\n".join(lines)


labels_latex = labels
y_true_latex = y_teste
y_pred_latex = previsoes

latex_matriz_confusao = make_latex_confusion_matrix(
    cm,
    labels_latex,
    "Matriz de Confus?o - Random Forest",
    "table:rf_completo_mc",
)
latex_relatorio_metricas = make_latex_metrics_report(
    y_true_latex,
    y_pred_latex,
    labels_latex,
    "Relat?rio de M?tricas do Modelo Random Forest",
    "table:rf_completo_metricas",
)

print(latex_matriz_confusao)
print("\n")
print(latex_relatorio_metricas)

\begin{table}[H]
    \centering
    \scriptsize
    \resizebox{\linewidth}{!}{
        \begin{tabular}{l|rrrrrrrrrrrrrrr}
            \hline
                                             & BENIGN      & Bot      & DDoS       & DoS GE    & Hulk       & Slowhttp  & Slowloris & FTP       & Heart  & Infil  & PortScan   & SSH       & Web Attack – Brute Force & Web Attack – Sql Injection & Web Attack – XSS \\
            \hline
            Real\_BENIGN                     & \ok{680481} & \err{6}  & \err{4}    & \err{1}   & \err{224}  & \err{8}   & 0         & 0         & 0      & 0      & \err{288}  & 0         & \err{2}                  & 0                          & 0                \\
            Real\_Bot                        & \err{36}    & \ok{528} & 0          & 0         & 0          & 0         & 0         & 0         & 0      & 0      & 0          & 0         & 0                        & 0                          & 0                \\
            Real\_DDoS                       & \err{21}    & 0        & \ok{38286} & 0         & 0          & 0         & 0         & 0         & 0      & 0      & 0          & 0         & 0                        & 0                          & 0                \\
            Real\_DoS GE                     & \err{5}     & 0        & 0          & \ok{3153} & \err{3}    & \err{2}   & 0         & 0         & 0      & 0      & 0          & 0         & 0                        & 0                          & 0                \\
            Real\_Hulk                       & \err{130}   & 0        & 0          & \err{4}   & \ok{69131} & 0         & 0         & 0         & 0      & 0      & \err{2}    & 0         & 0                        & 0                          & 0                \\
            Real\_Slowhttp                   & \err{7}     & 0        & 0          & 0         & 0          & \ok{1644} & \err{7}   & 0         & 0      & 0      & 0          & 0         & 0                        & 0                          & 0                \\
            Real\_Slowloris                  & \err{4}     & 0        & 0          & 0         & 0          & 0         & \ok{1753} & 0         & 0      & 0      & 0          & 0         & 0                        & 0                          & 0                \\
            Real\_FTP                        & 0           & 0        & 0          & 0         & 0          & 0         & 0         & \ok{2326} & 0      & 0      & 0          & 0         & 0                        & 0                          & 0                \\
            Real\_Heart                      & \err{2}     & 0        & 0          & 0         & 0          & 0         & 0         & 0         & \ok{4} & 0      & 0          & 0         & 0                        & 0                          & 0                \\
            Real\_Infil                      & \err{1}     & 0        & 0          & 0         & 0          & 0         & 0         & 0         & 0      & \ok{9} & 0          & 0         & 0                        & 0                          & 0                \\
            Real\_PortScan                   & \err{9}     & 0        & 0          & 0         & \err{6}    & 0         & 0         & 0         & 0      & 0      & \ok{47820} & 0         & \err{1}                  & 0                          & 0                \\
            Real\_SSH                        & \err{2}     & 0        & 0          & 0         & 0          & 0         & 0         & 0         & 0      & 0      & 0          & \ok{1819} & 0                        & 0                          & 0                \\
            Real\_Web Attack – Brute Force   & \err{6}     & 0        & 0          & 0         & 0          & 0         & 0         & 0         & 0      & 0      & 0          & 0         & \ok{390}                 & 0                          & \err{39}         \\
            Real\_Web Attack – Sql Injection & \err{4}     & 0        & 0          & \err{1}   & 0          & 0         & 0         & 0         & 0      & 0      & 0          & 0         & 0                        & \ok{1}                     & 0                \\
            Real\_Web Attack – XSS           & \err{14}    & 0        & 0          & 0         & 0          & 0         & 0         & 0         & 0      & 0      & \err{1}    & 0         & \err{55}                 & 0                          & \ok{123}         \\
            \hline
        \end{tabular}
    }
    \caption{Matriz de Confus?o - Random Forest}
    \label{table:rf_completo_mc}
\end{table}


\begin{table}[H]
    \centering
    \small
    \begin{tabular}{lrrrr}
        \hline
        Classe                     & Precis?o & Revoca??o & F1-score & Suporte \\
        \hline
        BENIGN                     & 1.00     & 1.00      & 1.00     & 681014  \\
        Bot                        & 0.99     & 0.94      & 0.96     & 564     \\
        DDoS                       & 1.00     & 1.00      & 1.00     & 38307   \\
        DoS GoldenEye              & 1.00     & 1.00      & 1.00     & 3163    \\
        DoS Hulk                   & 1.00     & 1.00      & 1.00     & 69267   \\
        DoS Slowhttptest           & 0.99     & 0.99      & 0.99     & 1658    \\
        DoS slowloris              & 1.00     & 1.00      & 1.00     & 1757    \\
        FTP-Patator                & 1.00     & 1.00      & 1.00     & 2326    \\
        Heartbleed                 & 1.00     & 0.67      & 0.80     & 6       \\
        Infiltration               & 1.00     & 0.90      & 0.95     & 10      \\
        PortScan                   & 0.99     & 1.00      & 1.00     & 47836   \\
        SSH-Patator                & 1.00     & 1.00      & 1.00     & 1821    \\
        Web Attack – Brute Force   & 0.87     & 0.90      & 0.88     & 435     \\
        Web Attack – Sql Injection & 1.00     & 0.17      & 0.29     & 6       \\
        Web Attack – XSS           & 0.76     & 0.64      & 0.69     & 193     \\
        \hline
        \textbf{Acur?cia}          & -        & 1.00      & -        & 848363  \\
        \textbf{M?dia Macro}       & 0.97     & 0.88      & 0.90     & 848363  \\
        \textbf{M?dia Ponderada}   & 1.00     & 1.00      & 1.00     & 848363  \\
        \hline
    \end{tabular}
    \caption{Relat?rio de M?tricas do Modelo Random Forest}
    \label{table:rf_completo_metricas}
\end{table}